name: React website

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'
  workflow_dispatch:
    paths:
      - 'client/**'

jobs:
  client:
    name: Test react website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/
    steps:
      - name: Checkout
        uses: actions/checkout@v4


  get_version:
    name: Get version
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Install jq
          run: sudo apt-get install -y jq
        - name: get version
          id: get_version
          run: | 
            version=`cat ./client/package.json | jq -r '.version'`
            echo "version=$version" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get_version.outputs.version }}

  publish-docker-image-ghcr:
    name: Publish Docker image (GHCR)
    needs: [client, get_version]
    uses: ./.github/workflows/docker-ghcr.yml
    with: 
      image-name: dtaas-web
      version: ${{ needs.get_version.outputs.version }}
      dockerfile: client.dockerfile
    secrets: inherit

  publish-docker-image-dockerhub:
    name: Publish Docker image (DockerHub)
    needs: [client, get_version]
    uses: ./.github/workflows/docker-dockerhub.yml
    with: 
      image-name: dtaas-web
      version: ${{ needs.get_version.outputs.version }}
      dockerfile: client.dockerfile
      readme-file: client/DOCKER.md
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_SCOPE: ${{ secrets.DOCKERHUB_SCOPE }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
