name: React website

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'
  workflow_dispatch:
    paths:
      - 'client/**'

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Install jq
          run: sudo apt-get install -y jq
        - name: get version
          id: get_version
          run: | 
            version=`cat ./client/package.json | jq -r '.version'`
            echo "version=$version" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get_version.outputs.version }}

  publish-docker-image:
    name: Publish Docker image
    needs: [get_version]
    uses: ./.github/workflows/docker.yml
    with: 
      image-name: aryanpingle/dtaas-web
      version: ${{ needs.get_version.outputs.version }}
      dockerfile: client.dockerfile
    secrets: inherit