name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        default: 'ghcr.io'
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
        default: 'latest'
      dockerfile:
        required: true
        type: string
      # Path from the project root to the package README
      readme:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: |
            type=image,name=dtaas-web,annotation.org.opencontainers.image.source=https://github.com/aryanpingle/LeetPy
          labels: |
            org.opencontainers.image.source=https://github.com/aryanpingle/LeetPy
          file: ./docker/${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}, ${{ inputs.registry }}/${{ inputs.image-name }}:latest
