# Reusable workflow for building and pushing a Docker Image to DockerHub

name: Build and Push Docker Image (GHCR)

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
        default: "latest"
      dockerfile:
        required: true
        type: string

env:
  ghcr-registry: ghcr.io
  ghcr-username: ${{ github.actor }}
  ghcr-password: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ghcr-registry }}
          username: ${{ env.ghcr-username }}
          password: ${{ env.ghcr-password }}

      - name: Check if version exists
        id: check_version
        run: |
          if docker manifest inspect ${{ env.ghcr-registry }}/${{ env.ghcr-username }}/${{ inputs.image-name }}:${{ inputs.version }} > /dev/null 2>&1; then
            echo "Version ${{ inputs.version }} already exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Version ${{ inputs.version }} does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        # if: env.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ env.ghcr-registry }}/${{ env.ghcr-username }}/${{ inputs.image-name }}:${{ inputs.version }}, \
            ${{ env.ghcr-registry }}/${{ env.ghcr-username }}/${{ inputs.image-name }}:latest
